version: '3.8'

services:
  parametric-drawing:
    build: .
    container_name: parametric-curve-drawing
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - VAPI_API_KEY=${VAPI_API_KEY:-}
      - LETTA_API_KEY=${LETTA_API_KEY:-}
    volumes:
      - ./static:/app/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
